default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: e_commerce_development
  url: <%= ENV['DEVELOPMENT_DB_URL'] %>

test:
  <<: *default
  database: e_commerce_test
  url: <%= ENV['TEST_DB_URL'] %>

production:
  <<: *default
  database: e_commerce_production
  url: <%= ENV['PRODUCTION_DB_URL'] %>
  username: e-commerce-api
  password: <%= ENV["E_COMMERCE_API_DATABASE_PASSWORD"] %>
